export const AFFIRMATIONS = [
  "I am capable of finding joy in small moments.",
  "My perspective is unique and valuable.",
  "I have everything I need to create a beautiful day.",
  "I am growing at my own perfect pace.",
  "I release what I cannot control.",
  "My mind is open to new possibilities.",
  "I deserve the good things that happen to me.",
  "Every day is a fresh start.",
  "I am surrounded by abundance.",
  "My potential is limitless.",
  "I choose peace over perfection.",
  "I am resilient and strong.",
  "I trust the process of my life.",
  "I radiate positive energy.",
  "My heart is open to gratitude.",
  "I am exactly where I need to be.",
  "I embrace the magic of the unknown.",
  "I am a magnet for good things.",
  "I find beauty in the ordinary.",
  "My energy creates my reality.",
  "I am worthy of love and respect.",
  "I am a force for good in the world.",
  "I celebrate my small victories.",
  "I am patient with myself.",
  "My life is a beautiful journey.",
  "I focus on what I can control.",
  "I am grateful for this moment.",
  "I invite joy into my daily life.",
  "I am doing my best, and that is enough.",
  "I have the power to create change.",
  "I welcome peace into my heart.",
  "I trust my inner wisdom.",
  "I am open to receiving love.",
  "I let go of limiting beliefs.",
  "My future is full of light.",
  "I am surrounded by love.",
  "I am proud of how far I've come.",
  "I bring light to those around me.",
  "I am thankful for my journey.",
  "I embrace my unique path.",
  "I am enough just as I am.",
  "I find strength in my challenges.",
  "I am open to the universe's gifts.",
  "I radiate confidence and grace.",
  "I choose to see the good today.",
  "I am safe and supported.",
  "My possibilities are endless.",
  "I am worthy of all the joy life offers.",
  "I create my own sunshine.",
  "I am deeply fulfilled by what I do."
];
